### ISSUE TITLE
Databaker is slow to process a02.py

### ISSUE THREAD

**Issue by StevenMaude** [sensiblecodeio/databaker#41]
We need to improve performance by 10x.  (currently at 130seconds for this simple example)

**Comment by goatchurchprime** [comment]
Problem has been isolated to an n^2 algorithm between the set of value cells and the sets of header cells.  Particularly bad in this example where there are 10000 cells and a header set of 500 cells [made up numbers].

**Comment by goatchurchprime** [comment]
Suppose obs = [ ob ] is the set of value cells and dims = [ ( headers, direction), ... ] is the set of dimensions, the current algorithm looks up the values per row:

```
for ob in obs:
   csv.write([ lookup(ob, direction, headers)  for header, direction in dimensions])
```
This needs to be restructured into a per-column based lookup:

```
def batchlookup(obs, header, direction):
   return [ lookup(ob, header, direction)  for ob in obs ]

columns = [ batchlookup(obs, h, d)  for h, d in dimensions ]

for i, ob in enumerate(obs):
   csv.write([ columns[j][i]  for j in range(len(dimensions))])
```

Then I can optimize batchlookup() using a couple of sorts and zipping the values up side by side.

**Comment by StevenMaude** [comment]
This was addressed; closing.
