### ISSUE TITLE
assignment of dimensions is not explicit

### ISSUE THREAD

**Issue by goatchurchprime** [sensiblecodeio/databaker#42]
The bag.dimension() function is problematic in both its use and implementation.  

Structure of current code:

```
def per_tab(tab):
   obs = tab.filter(...                # set of value cells
   h1 = tab.col('A').one_of(...        # set of header cells
   h1.dimension(name, direction...)    # instructions for going from a value to a header
   ...
   return obs
```

That h1.dimension() calls a class member function of the xypath.Table module (injected there when you run overrides.py).  This constructs a Dimension() object which injects the headers={} value into the h1.table object, and then appends itself into it.  

The only reason this association works is because h1.table===obs.table, otherwise the assignment would make no sense.  

What I would much rather have is something just more explicit, like this:

```
def per_tab(tab):
   obs = tab.filter(...                # set of value cells
   h1 = tab.col('A').one_of(...        # set of header cells
   d1 = Dimension(name, h1, direction...)    # instructions for going from a value to a header
   ...
   return obs, [d1, d2, ...]
```

... or something better, obviously.  But this explicit form would mean that it would be possible to compute stuff about the dimensions within the recipe code (eg specify that something would be sorted or aggregated).  

The idea is to structure it well enough to be able to pull in some of the subsequent operations back into the recipe for extra features.  For example, assign name lookups onto the header values or merge two excel tabs into the same csv output.  

It would be easy to maintain backwards compatibility with the current form, while removing obfuscation on the implementation.

**Comment by StevenMaude** [comment]
We have HDim now; closing.
