### ISSUE TITLE
Databaker uses considerable memory in certain cases

### ISSUE THREAD

**Issue by StevenMaude** [sensiblecodeio/databaker#49]
See: https://github.com/MikeData/crashingdatabaker

~~Running these recipes can take up to 20% memory on my 8 GB laptop under Linux, although they do complete, and not hang.~~

**Comment by MikeData** [comment]
try it with this one. same recipe but different source and params (if its gonna hang, this'll be the one). command line:

bake --preview ASHE_recipe.py "PROV - Work Region Occupation SOC10 (4) Table 15.1a   Weekly pay - Gross 2015.xls" "Weekly pay - Gross" D1 D2 "Not Classified" Bold N
bake --preview ASHE_recipe2.py "PROV - Work Region Occupation SOC10 (4) Table 15.1b   Weekly pay - Gross 2015 CV.xls" "Weekly pay - Gross" D1 D2 "Not Classified" Bold N

source data (in zip), here:
https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/regionbyoccupation4digitsoc2010ashetable15

just grab 1a and 1b. they all work the same

**Comment by StevenMaude** [comment]
To be fair, I'd removed `--preview`.

**Comment by StevenMaude** [comment]
Observations:

1. Changing [this line](https://github.com/sensiblecodeio/databaker/blob/392c577603dd7f0c4a83f4144310c8552ceeadd4/databaker/bake.py#L292) to remove the list creation reduces memory considerably:

```
no list:
User time (seconds): 255.19
System time (seconds): 1.61
Maximum resident set size (kbytes): 2073152
list (current code): 
User time (seconds): 252.13
System time (seconds): 1.95
Maximum resident set size (kbytes): 7024912
```

It only uses the list to see if there are any tabs; it's easy enough to instead set `tab` to `None` and then check whether `tab` is still `None` after the for loop. This doesn't fix the issue completely, but may help a bit.

2. `--preview` blows up memory usage considerably and slows down processing considerably (which could be due to swapping memory more often).

On my laptop, the CPU usage of bake kept varying but was seeming to take forever to do anything. It had got through to what I think was the final tab, and I think was hanging at the [saving Excel step](https://github.com/sensiblecodeio/databaker/blob/392c577603dd7f0c4a83f4144310c8552ceeadd4/databaker/bake.py#L337-L338) (it had created a Excel file, but I guess didn't complete).

So, it could be an issue with the Excel package databaker's using coupled with large spreadsheets.

I tried tinkering around adding this hacky code into the loop. It saves a new spreadsheet for each tab, which contains all tabs but with only one modified.

```python
if opt.preview:                                       
    writer = xlutils.copy.copy(tableset.workbook)     
    make_preview()                                    
    writer.save(filenames()['preview'] + str(tab_num))
```

Still takes a huge amount of time longer than without preview, but actually ran to completion:

```
User time (seconds): 880.13
System time (seconds): 5.03
Maximum resident set size (kbytes): 13881552
```

**Comment by StevenMaude** [comment]
For this particular recipe:

```python
# hacky
if tab_num > 1:
    del(writer)
    tableset = xypath.loader.table_set(filenames()['preview'], extension='xls')
    writer = xlutils.copy.copy(tableset.workbook)
```

inside the for loop helps reduce the usage *and* gives you all spreadsheet tabs in one sheet.

Again, with the `list` fix above:

```
User time (seconds): 932.42
System time (seconds): 4.55
Maximum resident set size (kbytes): 6829296
```

It's hacky as you need an existing output spreadsheet already written. So is recipe dependent: if you skip more than the first tab, you may not create the spreadsheet until a later tab, and this will fail since the file won't exist. Maybe you could just initially copy the spreadsheet first, then keep reopening/rewriting to it.

This seems sub-optimal too as we're constantly loading the spreadsheet each time, just so that we're able to close it and free up whatever large data structures `xlwt` is using.
 
I guess `xlwt`'s `flush_all_rows()` should give a similar kind of benefit, though not sure where to place that to be effective. I also suppose that we can be sure we're done with rows once we're writing the CSV row out.

**Comment by goatchurchprime** [comment]
The preview could run to completion and save out before any of the csv output files have been made.  The two don't depend on one another.  (preview is simply a colouring of the dimension sets.  these have been constructed before the first csv line is computed)

**Comment by StevenMaude** [comment]
NB: GNU `time` which I'd been using apparently has a bug where it reports four times memory usage; I'd expect the relative before/after values to be still meaningful.

**Comment by StevenMaude** [comment]
Added `flush_row_data` inside the `if opt.preview:` (after `make_preview`). Didn't seem to make any useful difference to memory usage, even though I know the method was actually get called (added debugging print to `xlwt`).

**Comment by StevenMaude** [comment]
Being tied to `xlrd` and `xlwt` is partly because:

* there are few options in Python for both reading *and* writing Excel files (`openpyxl` is another, but no idea how good it is), which we need: we need to open the existing Excel file, and then create a new, modified version.

* messytables (which `xypath` uses, which, in turn, `databaker` uses) uses `xlrd` to read the XLSX.

**Comment by StevenMaude** [comment]
On [this branch](https://github.com/sensiblecodeio/databaker/tree/hackily-reduce-excel-memory-usage), the same recipe (with `--preview`) takes about 20% memory (of 8 GB) as measured by `top`.

In one run, GNU `time` claimed `7637120 kbytes` which divided by 4, becomes 1.8 GB, which is also about 20% of 8 GB. Still not ideal and it's still slow, but seems reasonable that it might run on the ONS laptop without hanging, at least, which is an improvement.

Still not sure why flushing rows with `xlwt` has little/no impact on memory usage.

**Comment by StevenMaude** [comment]
Closing this as we addressed it.
